# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.network "private_network", ip: "172.28.128.31"

  # config.vm.box = 'windows_server_1709_docker_virtualbox.box'
  config.vm.box = "StefanScherer/windows_2019_docker"
  config.vm.guest = :windows
  config.vm.provider 'virtualbox' do |v, override|
    v.cpus = 4
    v.memory = 4096
    
  end

  config.vm.provision "shell", path: "provision.ps1" , privileged: true
end
