# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  # config.vbguest.auto_update = true
  config.vm.network "private_network", ip: "172.28.128.101"
  config.vm.box_url = 'http://downloads.dcos.io/dcos-vagrant/metadata.json'
  config.vm.box = 'mesosphere/dcos-centos-virtualbox'
  config.vm.provider 'virtualbox' do |v, override|
    v.cpus = 2
    v.memory = 4096
    
  end
  config.vm.provision "shell", path: "provision.sh"
end

